Repository webdev6/obscure-book-genres, pull requests merged in 2019-02, with the labels that each got.

#27 Add basic headings
  index.html
Labels: Dev, bug

#28 Paulina's temp heading
  index.html
Labels: Dev, bug

#32 Add basic headings
  index.html
Labels: Dev

#33 add basic headings
  index.html
Labels: Dev, bug

#34 new heading added
  index.html
Labels: Dev, bug

#40 favourite start
  favourites.html
  main.css
Labels: Content, Dev, bug
